
mlb_project:
  outputs:
    dev:
      type: duckdb
      path: 'md:motherduck_database'
      token: "{{ env_var('MOTHERDUCK_TOKEN') }}"
      database: motherduck_database
      schema: MLB_DATA  # Changed from 'main' to 'MLB_DATA'
      threads: 4
      extensions:
        - httpfs
        - parquet
        - motherduck
      settings:
        s3_region: us-east-2
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
  target: dev
