version: 2

models:
  - name: stg_mlb_team_rosters
    description: "Staging table for MLB team rosters with cleaned data types"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - player_id
            - team_id
            - season
    columns:
      - name: player_id
        description: "Unique identifier for each player"
        tests:
          - not_null
      - name: team_id
        description: "Unique identifier for each team"
        tests:
          - not_null
      - name: season
        description: "MLB season year"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 2020
              max_value: 2024
      - name: hitting_avg
        description: "Batting average"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1
              config:
                where: "hitting_avg is not null"