[destination.motherduck]
motherduck_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphY2todWxiZXJ0cGR4QGdtYWlsLmNvbSIsInNlc3Npb24iOiJqYWNraHVsYmVydHBkeC5nbWFpbC5jb20iLCJwYXQiOiJ2bXVoZ3B6ZWNqX0lZZDIwY0ZvNmh4NjJ3eE4yZmN5djZKX1dUeTF6TVdJIiwidXNlcklkIjoiNzVlOGYzOWUtNzU4Yy00Y2Y3LWFlNTQtYWQwNmJhZDlkMjIwIiwiaXNzIjoibWRfcGF0IiwicmVhZE9ubHkiOmZhbHNlLCJ0b2tlblR5cGUiOiJyZWFkX3dyaXRlIiwiaWF0IjoxNzQ2NzU2MjM0fQ.-YE5HF2rWb8daqtfv-KKmEpQn08NKZTB3h6-r5CpHeU"
S3_ACCESS_KEY_ID = "AKIAU72LF5JTAQCMRKV7"
S3_SECRET_ACCESS_KEY = "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"
AWS_UN = "dbt_user"
AWS_PW = "9rCY_8)5"